name: Notify Reviewers
on:
    push:
        branches: ["release/*"]
jobs:
    send_notification:
        runs-on: ubuntu-latest
        steps:
            - name: Send Notification
              env:
                  INTERNAL_NOTIFICATION_CHANNEL_API_ENDPOINT: ${{ secrets.INTERNAL_NOTIFICATION_CHANNEL_API_ENDPOINT }}
              run: |
                  COMMIT_ID=${{ github.sha }}
                  COMMIT_URL=${{ github.event.head_commit.url }}
                  COMMIT_AUTHOR=${{ github.event.pusher.name }}

                  MESSAGE="@channel\New commit on Gene UI Tokens: [#$COMMIT_ID]($COMMIT_URL) by $COMMIT_AUTHOR"

                  curl -X POST -H "Content-Type: application/json" -d "{\"text\": \"$MESSAGE\", \"username\": \"GitHub\", \"icon_url\": \"https://github.githubassets.com/favicons/favicon.png\"}" $INTERNAL_NOTIFICATION_CHANNEL_API_ENDPOINT
                  
